import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ExCheckboxEvent implements ActionListener {
    private JCheckBox checkBox1CheckBox;
    private JCheckBox checkBox2CheckBox;
    private JLabel label1;
    private JLabel label2;
    private JLabel label3;
    private JLabel label4;
    private JRadioButton opcao1RadioButton;
    private JRadioButton opcao2RadioButton;
    private JPanel panel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        checkBox2CheckBox = new JCheckBox();
        checkBox2CheckBox.setText("CheckBox 2");
        panel.add(checkBox2CheckBox, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label3 = new JLabel();
        label3.setText("Label");
        panel.add(label3, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label4 = new JLabel();
        label4.setText("Label");
        panel.add(label4, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        opcao1RadioButton = new JRadioButton();
        opcao1RadioButton.setSelected(true);
        opcao1RadioButton.setText("opcao 1");
        panel.add(opcao1RadioButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        opcao2RadioButton = new JRadioButton();
        opcao2RadioButton.setText("opcao 2");
        panel.add(opcao2RadioButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label2 = new JLabel();
        label2.setText("Label");
        panel.add(label2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        checkBox1CheckBox = new JCheckBox();
        checkBox1CheckBox.setSelected(false);
        checkBox1CheckBox.setText("CheckBox 1");
        panel.add(checkBox1CheckBox, new GridConstraints(0, 0, 3, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label1 = new JLabel();
        label1.setText("Label");
        panel.add(label1, new GridConstraints(0, 1, 3, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(opcao2RadioButton);
        buttonGroup.add(opcao1RadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    public ExCheckboxEvent() {
        label1.setText("caixa 1");
        label2.setText("caixa 2");
        label3.setText("opcao 1");
        label4.setText("opcao 2");
        checkBox1CheckBox.addActionListener(actionEvent -> {
            if (checkBox1CheckBox.isSelected())
                label1.setText("caixa 1 selecionada");
            else
                label1.setText("caixa 1 nao selecionada");
        });
        checkBox2CheckBox.addActionListener(actionEvent -> {
            if (checkBox2CheckBox.isSelected())
                label2.setText("caixa 2 selecionada");
            else
                label2.setText("caixa 2 nao selecionada");
        });
        opcao1RadioButton.addActionListener(new RadioListener(label3, label4, opcao1RadioButton));
        opcao2RadioButton.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        JRadioButton sourceRadio = (JRadioButton) actionEvent.getSource();
        if (opcao1RadioButton == sourceRadio) {
            label3.setText("radio 1 selecionado");
            label4.setText(("radio 2 nao selecionado"));
        } else {
            label4.setText("radio 2 selecionado");
            label3.setText(("radio 1 nao selecionado"));
        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("exemplo");
        frame.setContentPane(new ExCheckboxEvent().panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


}
